"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from . import runtime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Where bundled, read-only resources (templates, static files) are read
# from. Equal to BASE_DIR in normal development; points at the PyInstaller
# extraction directory when running as a frozen executable.
RESOURCE_DIR = runtime.get_resource_dir()

# Where persistent, writable data (the SQLite database) is stored. Equal to
# BASE_DIR in development so `db.sqlite3` keeps living next to manage.py;
# moves to a per-user AppData-style directory when frozen, since the
# PyInstaller bundle directory may be read-only. See config/runtime.py.
DATA_DIR = runtime.ensure_data_dir()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Read from the environment in production. The fallback below is for local
# development only; set SECRET_KEY in `.env` (see `.env.example`).
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-dev-only-change-me-before-deployment',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local development (`manage.py runserver`) and to
# False when running as a frozen desktop build, matching the existing dev
# behaviour exactly unless explicitly overridden with DJANGO_DEBUG.
DEBUG = os.environ.get('DJANGO_DEBUG', '' if runtime.FROZEN else 'True') == 'True'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'notes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # The project-level `templates/` dir, plus each app's `templates/`
        # dir listed explicitly. APP_DIRS below already finds the latter
        # via each app's on-disk path in normal development — but that
        # path resolution is unreliable once the app's source is frozen
        # into a PyInstaller archive, so listing them here directly
        # (resolved through RESOURCE_DIR, which already points at the
        # PyInstaller bundle when frozen) makes template loading robust
        # either way. Harmless duplication in dev: Django's loader simply
        # finds the same files through whichever path matches first.
        'DIRS': [
            RESOURCE_DIR / 'templates',
            RESOURCE_DIR / 'accounts' / 'templates',
            RESOURCE_DIR / 'notes' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    RESOURCE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
